name: Basic Workflow  # The name of the workflow, which appears in the GitHub Actions UI.

on: push, pull_request    # This defines the event that triggers the workflow. "workflow_dispatch" allows manual triggering.

jobs:
  basic-workflow:  # Defines a job named "basic-workflow".
    name: Basic Workflow  # The display name for the job in the GitHub Actions UI.
    runs-on: ubuntu-latest  # Specifies that this job should run on the latest Ubuntu environment.

    steps:
      - name: Checkout repository  # Step 1: Checks out the repository code so that subsequent steps have access to it.
        uses: actions/checkout@v4  # This is a prebuilt action that clones the repository into the workflow runner.

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Install Playwright Browsers
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps" --no-transfer-progress

      - name: Run tests
        run: mvn test

      - name: Publish report
        uses: phoenix-actions/test-reporting@v15
        with:
          name: 'Publish PW reports'
          path: target/surefire-reports/TEST*.xml
          reporter: java-junit
          list-test: all
          list-suites: all
          fail-on-error: true
          output-to: 'step-summary'